import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {ReactNode} from "react";
import { ThemeProvider } from "../components/ThemeProvider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: ReactNode; }>) {


    return (
        <html lang="ko" className="h-full" suppressHydrationWarning>
            <body className={`${inter.className} bg-none h-full dark:bg-slate-800`}>
            <ThemeProvider>
                {children}
            </ThemeProvider>
            </body>
        </html>
    );
}
