name: Docker Image CI

on:
  push:
    branches: [ 'master' ]

jobs:
  set-variables:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Environment Variables File for Production
        env:
          AUTH_USER: ${{secrets.AUTH_USER}}
          AUTH_PASS: ${{secrets.AUTH_PASS}}
          NOTION_TOKEN: ${{secrets.NOTION_TOKEN}}
          NOTION_DATABASE_ID: ${{secrets.NOTION_DATABASE_ID}}
        run: |
          echo "AUTH_USER=$AUTH_USER" >> .env.production
          echo "AUTH_PASS=$AUTH_PASS" >> .env.production
          echo "NOTION_TOKEN=$NOTION_TOKEN" >> .env.production
          echo "NOTION_DATABASE_ID=$NOTION_DATABASE_ID" >> .env.production
          tar -czf env.tar.gz .env.production

      - name: Upload Environment Variables Archive
        uses: actions/upload-artifact@v3
        with:
          name: env-file
          path: env.tar.gz

  build-and-push:
    runs-on: ubuntu-latest
    needs: set-variables
    steps:
      - uses: actions/checkout@v3
      - name: Download Environment Variables Archive
        uses: actions/download-artifact@v3
        with:
          name: env-file

      - name: Extract Environment Variables
        run: |
          tar -xzf env.tar.gz

      - name: Build the Docker image
        run: docker build -t nextjs-portfolio .

      - name: taging
        run: docker tag nextjs-portfolio:latest kuhj7593/nextjs-portfolio:latest

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Push to Dockerhub
        run: docker push kuhj7593/nextjs-portfolio:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.ORACLE_CLOUD_DOMAIN}}
          username: ${{secrets.ORACLE_CLOUD_USER}}
          key: ${{secrets.ORACLE_CLOUD_KEY}}
          script: |
            sh /home/ubuntu/portfolio/deploy.sh
