name: Docker Image CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build the Docker image
        run: docker build -t nextjs-portfolio .
      - name: taging
        run: docker tag nextjs-portfolio:latest kuhj7593/nextjs-portfolio:latest
      - name: Push to Dockerhub
        run: docker push kuhj7593/nextjs-portfolio:latest
