name: Docker Image CI

on:
  push:
    branches: [ 'master' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Generate Environment Variables File for Production
        env:
          AUTH_USER: ${{secrets.AUTH_USER}}
          AUTH_PASS: ${{secrets.AUTH_PASS}}
        run: |
          echo "AUTH_USER=$AUTH_USER" >> .env.production
          echo "AUTH_PASS=$AUTH_PASS" >> .env.production
          ls -al

      - name: Build the Docker image
        run: docker build -t nextjs-portfolio .

      - name: taging
        run: docker tag nextjs-portfolio:latest kuhj7593/nextjs-portfolio:latest

      - name: Push to Dockerhub
        run: docker push kuhj7593/nextjs-portfolio:latest

      - name: deploy
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{secrets.ORACLE_CLOUD_DOMAIN}}
          username: ${{secrets.ORACLE_CLOUD_USER}}
          key: ${{secrets.ORACLE_CLOUD_KEY}}
          script: |
            sh /home/ubuntu/portfolio/deploy.sh
